<?php

/**
 * sfGuardUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Bariloche.com.ar
 * @subpackage model
 * @author     julian[at]animus.com.ar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function setPassword($password)
	{
		if (strlen($password) == 40)
		{
			return $this->_set('password', $password);
		}

		return parent::setPassword($password);
	}

}
