<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    function findUser($q, $limit) {
	$q =  $this->createQuery('u')
	->where('first_name LIKE ?', '%' . $q . '%')
	->orWhere('last_name LIKE ?', '%' . $q . '%')
	->orWhere('username LIKE ?', '%' . $q . '%')
	->addOrderBy('last_name')
	->limit($limit)
	->execute();

	$users = array();
	foreach ($q as $user) 
	{
	    $users[$user->getId()] = $user->getFirstName()." ".$user->getLastName();
	}
	return $users;
    }
}