<?php

/**
 * sfGuardUserPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Bariloche.com.ar
 * @subpackage model
 * @author     julian[at]animus.com.ar
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserPermission extends PluginsfGuardUserPermission
{
}
