generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions
    # extra: [show, print, export]

    config:
      actions: ~
      fields: ~
      list:
        title: Litado de usuarios
        display: [username, first_name, last_name]
        object_actions:
          _edit: ~
          _delete:
            confirm: Esta seguro?
      filter:  ~
      form:
        display: 
          Datos: [first_name, last_name, email_address]
          Datos de acceso: [username, password, password_again, is_active]
          Permisos: [is_super_admin, groups_list, permissions_list]
        class: sfGuardUserAdminForm
      edit:
        title: Editando usuario
      new:
        title: Nuevo usuario
      show:    ~
